---
  repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
        - id: trailing-whitespace
        - id: check-yaml
        - id: check-json
        - id: end-of-file-fixer
        - id: requirements-txt-fixer
        - id: check-merge-conflict
    - repo: local
      hooks:
        - id: format
          name: format
          entry: make format
          language: system
          always_run: true
        - id: check
          name: check
          entry: make check
          language: system
          always_run: true
          verbose: true
          fail_fast: true
          pass_filenames: false
